version: '3.8'

services:

  chatbot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    image: telegram-bot:0.1
    container_name: telegram-bot
    expose:
      - 8000
    env_file:
      - ./.env.bot
    networks:
      - tresaurus-app-public-network
    labels:
      - com.compose.app=tresaurus-app

#  web:
#    build:
#      context: ./web_app
#      dockerfile: Dockerfile
#    image: webapp:0.1
#    container_name: web_app
#    ports:
#      - "5000:5000"
#    depends_on:
#      - mongo_db
#    env_file:
#      - ./.env.web-app
#    networks:
#      - tresaurus-app-public-network
#    labels:
#      - com.compose.app=tresaurus-app

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api:0.1
    container_name: api
    ports:
      - "8475:8000"
    depends_on:
      - mongo_db
    env_file:
      - ./.env.api
    networks:
      - tresaurus-app-public-network
    labels:
      - com.compose.app=tresaurus-app

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - tresaurus-app-public-network
    labels:
      - com.compose.app=tresaurus-app

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8081:8081"
    depends_on:
      - mongo_db
    env_file:
      - ./.env.express
    networks:
      - tresaurus-app-public-network
    labels:
      - com.compose.app=tresaurus-app

volumes:
  mongodb-data:
    labels:
      - com.compose.app=tresaurus-app

networks:
  tresaurus-app-public-network:
    labels:
      - com.compose.app=tresaurus-app
