version: '3.8'

services:

  chatbot:
    build:
      context: ./tg_app
      dockerfile: Dockerfile
    container_name: tg_app
    labels:
      - com.compose.app=tresaurus-app
    expose:
      - 8000
    env_file:
      - ./.env.tg-app
    networks:
      - application

  web:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    container_name: web_app
    labels:
      - com.compose.app=tresaurus-app
    ports:
      - "5000:5000"
    depends_on:
      - mongo_db
    env_file:
      - ./.env.web-app
    networks:
      - application

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    labels:
      - com.compose.app=tresaurus-app
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - application

  mongo-express:
    image: mongo-express
    labels:
      - com.compose.app=tresaurus-app
    ports:
      - "8081:8081"
    depends_on:
      - mongo_db
    env_file:
      - ./.env.mongo-express
    networks:
      - application

networks:
  application:
