version: '3.8'

services:

  chatbot:
    build:
      context: ./tg_app
      dockerfile: Dockerfile
    image: chatbot:0.1
    container_name: tg_app
    expose:
      - 8000
    env_file:
      - ./.env.tg-app
    networks:
      - tresaurus-app-public-network
    labels:
      - com.compose.app=tresaurus-app

  web:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    image: webapp:0.1
    container_name: web_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo_db
    env_file:
      - ./.env.web-app
    networks:
      - tresaurus-app-public-network
    labels:
      - com.compose.app=tresaurus-app

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopasswd
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - tresaurus-app-public-network
    labels:
      - com.compose.app=tresaurus-app

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopasswd
      ME_CONFIG_BASICAUTH_USERNAME: mongoadmin
      ME_CONFIG_BASICAUTH_PASSWORD: mongopasswd
    ports:
      - "8081:8081"
    depends_on:
      - mongo_db
    env_file:
      - ./.env.mongo-express
    networks:
      - tresaurus-app-public-network
    labels:
      - com.compose.app=tresaurus-app

volumes:
  mongodb-data:
    labels:
      - com.compose.app=tresaurus-app

networks:
  tresaurus-app-public-network:
    labels:
      - com.compose.app=tresaurus-app
